"""Create chat_logs table

Revision ID: 477bfdbbe00c
Revises: 
Create Date: 2024-12-09 21:16:24.261484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477bfdbbe00c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_logs')
    # ### end Alembic commands ###
